[build]
# to have a `base` variable but you do need the `publish` and `command` variables.
publish = "public"
command = "zola build"

[build.environment]
# Set the version name that you want to use and Netlify will automatically use it.
ZOLA_VERSION = "0.17.0"
