[[project]]
name = "Gas Optimization Handbook"
desc = "In-depth explanations of commonly used optimization strategies."
tags = ["gas optimization"]
links = [
  { name = "github", url = "https://github.com/0xlgtm/gas-optimization-handbook" },
]
